### ISSUE TITLE
Issues when using on iPadOS App

### ISSUE THREAD

**Issue by wang01h2** [NicFontana/SwiftUI-CustomTabView#3]
Hello Niccolò,
I encountered an issue while developing an iPadOS app using [SwiftUI-CustomTabView](https://github.com/NicFontana/SwiftUI-CustomTabView/tree/main). I cannot switch in order without using NavigationView{}, and using it separates my views. Is there a method that allows me to switch without using NavigationView{}?

**Comment by NicFontana** [comment]
Hello, sorry what do you need to switch?

Could you please share some code that better explains the problem?

**Comment by wang01h2** [comment]
> Hello, sorry what do you need to switch?
> 
> Could you please share some code that better explains the problem?

Thank you for your reply, I found that there was an issue with my code, which has now been resolved.
